#!/bin/bash

# SIMPLE MANUAL DEPLOYMENT GUIDE
# Phase 2 Backend to Hugging Face

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     📦 PHASE 2 - MANUAL DEPLOYMENT (5 MINUTES)              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Git push nahi chal raha, toh manual upload karte hain."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 STEP 1: Files Upload Karo"
echo ""
echo "1. Is link par jao:"
echo "   https://huggingface.co/spaces/Amber-Asif/todo-app-phase-2"
echo ""
echo "2. 'Files' tab click karo"
echo ""
echo "3. Purani files delete karo (agar hain toh):"
echo "   - .gitattributes"
echo "   - README.md"
echo ""
echo "4. 'Add file' → 'Upload files' click karo"
echo ""
echo "5. Yeh files upload karo (ek ek karke ya sab ek saath):"
echo ""
echo "   FROM: /mnt/e/Hackathon-2/temp-hf-deploy/"
echo ""
echo "   Files to upload:"
echo "   ✓ Dockerfile"
echo "   ✓ README.md"
echo "   ✓ main.py"
echo "   ✓ pyproject.toml"
echo "   ✓ uv.lock"
echo "   ✓ alembic.ini"
echo "   ✓ src/ (folder with all files inside)"
echo "   ✓ alembic/ (folder with all files inside)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔐 STEP 2: Environment Variables Set Karo"
echo ""
echo "1. Settings par jao:"
echo "   https://huggingface.co/spaces/Amber-Asif/todo-app-phase-2/settings"
echo ""
echo "2. 'Variables and secrets' section mein jao"
echo ""
echo "3. Yeh 3 secrets add karo:"
echo ""
echo "   Name: DATABASE_URL"
echo "   Value: <your_neon_connection_string>?sslmode=require"
echo ""
echo "   Name: AUTH_SECRET_KEY"
echo "   Value: 18d4R14KL0ZO8uNvnw29IoJvn9iLtrkbzrCwEdGMCSg"
echo ""
echo "   Name: DEBUG"
echo "   Value: false"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏳ STEP 3: Build Wait Karo (2-5 minutes)"
echo ""
echo "1. 'Logs' tab check karo"
echo "2. Build complete hone ka wait karo"
echo "3. Success message: 'Application startup complete'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ STEP 4: Test Karo"
echo ""
echo "Browser mein kholo:"
echo "   https://amber-asif-todo-app-phase-2.hf.space/health"
echo "   https://amber-asif-todo-app-phase-2.hf.space/docs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 Files location: /mnt/e/Hackathon-2/temp-hf-deploy/"
echo ""
echo "🎉 Done! Bas 5 minutes mein deploy ho jayega!"
