"""Add composite index on user_id and status

Revision ID: f87cb5757944
Revises: 593393675e3b
Create Date: 2026-02-06 00:04:41.747794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87cb5757944'
down_revision: Union[str, Sequence[str], None] = '593393675e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_user_id_status', 'task', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_user_id_status', table_name='task')
    # ### end Alembic commands ###
